[package]
name = "spikememe"
version = "1.0.0"
authors = []

[addresses]

spike = "0xfec116479f1fd3cb9732cc768e6061b0e45b178a610b9bc23c2143a6493e794"

[dev-addresses]

[dependencies.SupraFramework]
git = "https://github.com/Entropy-Foundation/aptos-core.git"
rev = "5e7eed4ca4687e87862aba2f8cf29cae1308fa5a"
subdir = "aptos-move/framework/supra-framework"

[dev-dependencies]
