[package]
name = "spikememe"
version = "1.0.0"
authors = []

[addresses]

spike = "0xfec116479f1fd3cb9732cc768e6061b0e45b178a610b9bc23c2143a6493e794"

[dev-addresses]

[dependencies.SupraFramework]
git = "https://github.com/Entropy-Foundation/aptos-core.git"
rev = "249843f62514449665a7ad85e7c86b7355999c08"
subdir = "aptos-move/framework/supra-framework"

[dev-dependencies]
