[package]
name = "pump_spike"
version = "1.0.0"
authors = []

[addresses]

pump = "0x5d7f79da44885dfd543f81139cff25fb43121e7ae03ebd720f9ac9e6449dd1a5"
spike_amm = "0xfeff8d092002f46554aae4018d6c3ab055168d9782563c57c8b0557c7eb42426"
lp_treasury = "0x5d7f79da44885dfd543f81139cff25fb43121e7ae03ebd720f9ac9e6449dd1a5"

[dev-addresses]

[dependencies.SupraFramework]
git = "https://github.com/Entropy-Foundation/aptos-core.git"
rev = "dev"
subdir = "aptos-move/framework/supra-framework"

[dependencies.AptosTokenObjects]
git = "https://github.com/Entropy-Foundation/aptos-core.git"
rev = "dev"
subdir = "aptos-move/framework/aptos-token-objects"

[dependencies.AptosToken]
git = "https://github.com/Entropy-Foundation/aptos-core.git"
rev = "dev"
subdir = "aptos-move/framework/aptos-token"

[dependencies.amm]
git = "https://github.com/SNABUR/spike_amm.git"
rev = "main"

[dev-dependencies]
